=== khubaibeh/pbi/src/pbi/defs/report/report/schema-3.3.0.json
{
	"$id": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.3.0/schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Report",
	"description": "Defines a report and its pages, visuals, settings, and additional information.",
	"type": "object",
	"properties": {
		"$schema": {
			"description": "Defines the schema to use for an item.",
			"type": "string",
			"const": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.3.0/schema.json"
		},
		"themeCollection": {
			"$ref": "#/definitions/ThemeCollection",
			"description": "Define a theme (built-in and/or a custom theme) to be used for this report."
		},
		"filterConfig": {
			"description": "Filters that apply to the entire report (all pages and all visuals).",
			"$ref": "../../filterConfiguration/1.3.0/schema-embedded.json"
		},
		"objects": {
			"description": "Specifies the formatting to be set for different \"objects\" of a report.",
			"$ref": "#/definitions/ReportFormattingObjects"
		},
		"reportSource": {
			"description": "Defines how the report was created.",
			"type": "string",
			"anyOf": [
				{
					"const": "Default",
					"description": "A blank report generated by Power BI apps."
				},
				{
					"const": "SharePoint",
					"description": "A quick create report created from a SharePointList."
				},
				{
					"const": "Teams",
					"description": "A quick create report created from Teams."
				},
				{
					"const": "QuickCreate",
					"description": "A quick create report created from Power BI app."
				},
				{
					"const": "EmbedQuickCreate",
					"description": "A quick create report created from an embedded source."
				},
				{
					"const": "Datamart",
					"description": "A new report created from Datamart."
				},
				{
					"const": "DataExplore",
					"description": "A report generated by exporting an Exploration as a report."
				}
			]
		},
		"publicCustomVisuals": {
			"description": "Names of the custom visuals used in this report from AppSource.",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"resourcePackages": {
			"description": "Set of resources used within this report.",
			"type": "array",
			"items": {
				"$ref": "#/definitions/ResourcePackage"
			}
		},
		"organizationCustomVisuals": {
			"description": "Names and metadata of the organization approved custom visuals used in the report.",
			"type": "array",
			"items": {
				"$ref": "#/definitions/OrganizationCustomVisual"
			}
		},
		"annotations": {
			"description": "Additional information to be saved (for example comments, readme, etc) for this report.",
			"type": "array",
			"items": {
				"$ref": "#/definitions/Annotation"
			}
		},
		"dataSourceVariables": {
			"description": "A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.",
			"type": "string"
		},
		"settings": {
			"description": "Settings for the report.",
			"$ref": "#/definitions/ExplorationSettings"
		},
		"slowDataSourceSettings": {
			"description": "Settings for slow data sources (for example turning all apply all button for filters).",
			"$ref": "#/definitions/ExplorationSlowDataSourceSettings"
		}
	},
	"additionalProperties": false,
	"required": ["$schema", "themeCollection"],
	"definitions": {
		"ThemeCollection": {
			"type": "object",
			"properties": {
				"baseTheme": {
					"description": "Defines the base monthly release themes shipped with Power BI.",
					"$ref": "#/definitions/ThemeMetadata"
				},
				"customTheme": {
					"description": "Defines a custom theme that is applied on top of the base theme.\nProperties not defined in the custom theme will fallback to using the base theme.",
					"$ref": "#/definitions/ThemeMetadata"
				}
			},
			"additionalProperties": false
		},
		"ThemeMetadata": {
			"type": "object",
			"properties": {
				"name": {
					"description": "Name of the theme.",
					"type": "string"
				},
				"reportVersionAtImport": {
					"$ref": "#/definitions/ThemeVersion",
					"description": "Versions when the theme was added to the report."
				},
				"type": {
					"$ref": "#/definitions/ThemeResourcePackageType",
					"description": "Built-in or user specific custom theme."
				}
			},
			"additionalProperties": false,
			"required": ["name", "reportVersionAtImport", "type"]
		},
		"ThemeVersion": {
			"type": "object",
			"properties": {
				"visual": {
					"description": "The max visual container version at import.",
					"pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
					"type": "string"
				},
				"page": {
					"description": "The max page version at import.",
					"pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
					"type": "string"
				},
				"report": {
					"description": "The max report version at import.",
					"pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": ["page", "report", "visual"]
		},
		"ThemeResourcePackageType": {
			"type": "string",
			"anyOf": [
				{
					"const": "RegisteredResources",
					"description": "Additional resources not bundled as part of the Power BI application."
				},
				{
					"const": "SharedResources",
					"description": "Resources bundled as part of the Power BI applications."
				}
			]
		},
		"ReportFormattingObjects": {
			"type": "object",
			"properties": {
				"outspacePane": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"selector": {
								"description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
								"$ref": "../../formattingObjectDefinitions/1.5.0/schema.json#/definitions/Selector"
							},
							"properties": {
								"$ref": "#/definitions/OutspacePane",
								"description": "Describes the properties of the object to apply formatting changes to."
							}
						},
						"additionalProperties": false,
						"required": ["properties"]
					}
				},
				"section": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"selector": {
								"description": "Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.",
								"$ref": "../../formattingObjectDefinitions/1.5.0/schema.json#/definitions/Selector"
							},
							"properties": {
								"$ref": "#/definitions/Section",
								"description": "Describes the properties of the object to apply formatting changes to."
							}
						},
						"additionalProperties": false,
						"required": ["properties"]
					}
				}
			},
			"additionalProperties": false
		},
		"OutspacePane": {
			"type": "object",
			"properties": {
				"expanded": {},
				"visible": {}
			},
			"additionalProperties": false
		},
		"Section": {
			"type": "object",
			"properties": {
				"verticalAlignment": {}
			},
			"additionalProperties": false
		},
		"ResourcePackage": {
			"type": "object",
			"properties": {
				"id": {
					"type": "number"
				},
				"name": {
					"type": "string"
				},
				"type": {
					"$ref": "#/definitions/ResourcePackageType"
				},
				"items": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ResourcePackageItem"
					}
				},
				"disabled": {
					"type": "boolean"
				}
			},
			"additionalProperties": false,
			"required": ["items", "name", "type"]
		},
		"ResourcePackageType": {
			"type": "string",
			"anyOf": [
				{
					"const": "CustomVisual"
				},
				{
					"const": "RegisteredResources"
				},
				{
					"const": "SharedResources"
				},
				{
					"const": "OrganizationalStoreCustomVisual"
				}
			]
		},
		"ResourcePackageItem": {
			"type": "object",
			"properties": {
				"id": {
					"type": "number"
				},
				"name": {
					"type": "string"
				},
				"path": {
					"type": "string"
				},
				"type": {
					"$ref": "#/definitions/ResourcePackageItemType"
				}
			},
			"additionalProperties": false,
			"required": ["name", "path", "type"]
		},
		"ResourcePackageItemType": {
			"type": "string",
			"anyOf": [
				{
					"const": "CustomVisualJavascript"
				},
				{
					"const": "CustomVisualsCss"
				},
				{
					"const": "CustomVisualScreenshot"
				},
				{
					"const": "CustomVisualIcon"
				},
				{
					"const": "CustomVisualWatermark"
				},
				{
					"const": "CustomVisualMetadata"
				},
				{
					"const": "Image"
				},
				{
					"const": "ShapeMap"
				},
				{
					"const": "CustomTheme"
				},
				{
					"const": "BaseTheme"
				},
				{
					"const": "DashboardTheme"
				},
				{
					"const": "DashboardBaseTheme"
				},
				{
					"const": "HighContrastTheme"
				},
				{
					"const": "AppNavigation"
				},
				{
					"const": "AppTheme"
				},
				{
					"const": "AppBaseTheme"
				}
			]
		},
		"OrganizationCustomVisual": {
			"type": "object",
			"properties": {
				"name": {
					"description": "Name of the organization custom visual.",
					"type": "string"
				},
				"path": {
					"description": "Path where the custom visual is stored.",
					"type": "string"
				},
				"disabled": {
					"description": "Signifies if the custom visual is disabled by the organization.",
					"type": "boolean"
				}
			},
			"additionalProperties": false,
			"required": ["name", "path"]
		},
		"Annotation": {
			"type": "object",
			"properties": {
				"name": {
					"description": "Unique name for the annotation.",
					"type": "string"
				},
				"value": {
					"description": "A value for this annotation.",
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": ["name", "value"]
		},
		"ExplorationSettings": {
			"type": "object",
			"properties": {
				"isPersistentUserStateDisabled": {
					"description": "Disable saving state of changes to a report as report viewers modify slicers and filters.",
					"type": "boolean"
				},
				"hideVisualContainerHeader": {
					"description": "Hide visual container header in view mode of the report.",
					"type": "boolean"
				},
				"useStylableVisualContainerHeader": {
					"description": "Use the new visual container header that is formattable.",
					"type": "boolean"
				},
				"exportDataMode": {
					"description": "When exporting data, what should be exported.",
					"type": "string",
					"anyOf": [
						{
							"const": "AllowSummarized",
							"description": "Only allow summarized data."
						},
						{
							"const": "AllowSummarizedAndUnderlying",
							"description": "Allow underlying and summarized data."
						},
						{
							"const": "None",
							"description": "Don't allow exporting data."
						}
					]
				},
				"isReportAnnotationsDisabled": {
					"description": "Commenting is disabled for this report.",
					"type": "boolean"
				},
				"defaultFilterActionIsDataFilter": {
					"description": "When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.",
					"type": "boolean"
				},
				"defaultDrillFilterOtherVisuals": {
					"description": "When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.",
					"type": "boolean"
				},
				"useCrossReportDrillthrough": {
					"description": "Allow drill-through from other reports to this report.",
					"type": "boolean"
				},
				"allowChangeFilterTypes": {
					"description": "Disables changing the type of filter in view mode.",
					"type": "boolean"
				},
				"allowInlineExploration": {
					"description": "Allows personalize this visual for the report in view mode.",
					"type": "boolean"
				},
				"useEnhancedTooltips": {
					"description": "Uses better tooltips for the visuals in this report.",
					"type": "boolean"
				},
				"useScaledTooltips": {
					"description": "If enabled, the tooltip will scale to match canvas zoom.",
					"type": "boolean"
				},
				"filterPaneHiddenInEditMode": {
					"description": "Hide the filter pane in view mode.",
					"type": "boolean"
				},
				"disableFilterPaneSearch": {
					"description": "Disables the search bar in filter pane.",
					"type": "boolean"
				},
				"pagesPosition": {
					"description": "Default location where the page navigator is shown.",
					"type": "string",
					"anyOf": [
						{
							"const": "PagesPane",
							"description": "In a pane next to the report."
						},
						{
							"const": "Bottom",
							"description": "In a toolbar below the report."
						}
					]
				},
				"allowAutomatedInsightsNotification": {
					"description": "Allow generating insights for the report in the background on data refresh.",
					"type": "boolean"
				},
				"useDefaultAggregateDisplayName": {
					"description": "Show the default aggregate in display names for summarized data.",
					"type": "boolean"
				},
				"enableDeveloperMode": {
					"description": "Enables developer mode for testing private custom visuals.",
					"type": "boolean"
				},
				"pauseQueries": {
					"description": "Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
					"type": "boolean"
				},
				"queryLimitOption": {
					"description": "Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits",
					"type": "string",
					"anyOf": [
						{
							"const": "None"
						},
						{
							"const": "Shared"
						},
						{
							"const": "Premium"
						},
						{
							"const": "SQLServerAS"
						},
						{
							"const": "AzureAS"
						},
						{
							"const": "Custom"
						},
						{
							"const": "Auto"
						}
					]
				},
				"customMemoryLimit": {
					"description": "If custom query limit is applied, this value defines the memory limit.",
					"type": "string"
				},
				"customTimeoutLimit": {
					"description": "If custom query limit is applied, this value defines the timeout limit.",
					"type": "string"
				},
				"fieldParameterReportSettings": {
					"description": "Settings that will control the field parameter across all the visual in the report",
					"$ref": "#/definitions/FieldParameterReportSettings"
				},
				"defaultDataExplorePerspective": {
					"description": "The default perspective that can be used with the report.",
					"type": "string"
				},
				"locale": {
					"description": "Report specific locale that takes precedence over browser and os locale.",
					"type": "string"
				},
				"defaultDisplayUnitsToNone": {
					"description": "Report specific setting to default display units to none.",
					"type": "boolean"
				}
			},
			"additionalProperties": false
		},
		"FieldParameterReportSettings": {
			"type": "object",
			"properties": {
				"skipHierarchyLevelPersistence": {
					"description": "If disabled, during parameter resolution, the hierarchy level and expand/collapse state of the visual won't be persisted",
					"type": "boolean"
				}
			},
			"additionalProperties": false
		},
		"ExplorationSlowDataSourceSettings": {
			"type": "object",
			"properties": {
				"isCrossHighlightingDisabled": {
					"description": "Disable cross highlights.",
					"type": "boolean"
				},
				"isSlicerSelectionsButtonEnabled": {
					"description": "Adds 'apply' button to slicers.",
					"type": "boolean"
				},
				"isFilterSelectionsButtonEnabled": {
					"description": "Adds 'apply' button to filters.",
					"type": "boolean"
				},
				"isFieldWellButtonEnabled": {
					"description": "Adds 'apply' button to field changes.",
					"type": "boolean"
				},
				"isApplyAllButtonEnabled": {
					"description": "Adds an apply all button.",
					"type": "boolean"
				}
			},
			"additionalProperties": false
		}
	}
}

=== khubaibeh/pbi/test/fixtures/report/3.3/success.json
{
	"$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.3.0/schema.json",
	"themeCollection": {
		"baseTheme": {
			"name": "CY24SU02",
			"reportVersionAtImport": {
				"visual": "1.8.89",
				"report": "2.0.89",
				"page": "1.3.89"
			},
			"type": "SharedResources"
		},
		"customTheme": {
			"name": "CustomTheme1.json",
			"reportVersionAtImport": {
				"visual": "1.8.98",
				"report": "2.0.98",
				"page": "1.3.98"
			},
			"type": "RegisteredResources"
		}
	},
	"objects": {
		"section": [
			{
				"properties": {
					"verticalAlignment": {
						"expr": {
							"Literal": {
								"Value": "'Top'"
							}
						}
					}
				}
			}
		],
		"outspacePane": [
			{
				"properties": {
					"expanded": {
						"expr": {
							"Literal": {
								"Value": "false"
							}
						}
					},
					"visible": {
						"expr": {
							"Literal": {
								"Value": "true"
							}
						}
					}
				}
			}
		]
	},
	"publicCustomVisuals": [
		"deneb7E15AEF80B9E4D4F8E12924291ECE89A",
		"htmlContent443BE3AD55E043BF878BED274D3A6855"
	],
	"resourcePackages": [
		{
			"name": "ChicletSlicer1448559807354",
			"type": "CustomVisual",
			"items": [
				{
					"name": "ChicletSlicer1448559807354.pbiviz.json",
					"path": "ChicletSlicer1448559807354.pbiviz.json",
					"type": "CustomVisualMetadata"
				}
			]
		},
		{
			"name": "RegisteredResources",
			"type": "RegisteredResources",
			"items": [
				{
					"name": "Image1.png",
					"path": "Image1.png",
					"type": "Image"
				},
				{
					"name": "CustomTheme1.json",
					"path": "CustomTheme1.json",
					"type": "CustomTheme"
				}
			]
		},
		{
			"name": "SharedResources",
			"type": "SharedResources",
			"items": [
				{
					"name": "CY24SU02",
					"path": "BaseThemes/CY24SU02.json",
					"type": "BaseTheme"
				}
			]
		}
	],
	"settings": {
		"useStylableVisualContainerHeader": true,
		"exportDataMode": "AllowSummarized",
		"defaultFilterActionIsDataFilter": true,
		"defaultDrillFilterOtherVisuals": true,
		"allowChangeFilterTypes": true,
		"useEnhancedTooltips": true,
		"queryLimitOption": "None",
		"customMemoryLimit": "1048576",
		"customTimeoutLimit": "225"
	},
	"slowDataSourceSettings": {
		"isCrossHighlightingDisabled": false,
		"isSlicerSelectionsButtonEnabled": false,
		"isFilterSelectionsButtonEnabled": false,
		"isFieldWellButtonEnabled": false,
		"isApplyAllButtonEnabled": false
	}
}
